# paths
# MODULES = ../../modules
# INCLUDE = ../../include



# Αρχεία .o
OBJS = sniffer.o sniffer2.o

# Το εκτελέσιμο πρόγραμμα
EXEC = sniffer

# Arguments we need
ARGS = 



$(EXEC): $(OBJS)
	g++ $(OBJS) -o $(EXEC)


run: $(EXEC)
	./$(EXEC) $(ARGS)